language: python

dist: xenial

# https://www.riverbankcomputing.com/pipermail/pyqt/2019-February/041363.html
addons:
  apt:
    packages:
    - libxkbcommon-x11-0

env:
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - XVFBARGS="-screen 0 1280x1024x24"
    - BUILD_DEP="pip~=19.3.1 wheel"
    - TEST_DEP="PyQt5~=5.9.2"

matrix:
  fast_finish: true
  include:
    - python: '3.6'

    - python: '3.7'
      env:
        - TEST_DEP="PyQt5~=5.12.1 PyQtWebEngine~=5.12.1"

    - python: '3.8'
      env:
        - TEST_DEP="PyQt5~=5.14.0 PyQtWebEngine~=5.14.0"

cache:
  pip: true

install:
  - pip install $BUILD_DEP
  - pip --version
  - pip list --format=freeze
  - pip install $TEST_DEP
  - pip install -e .

script:
  - pip list --format=freeze
  - xvfb-run -a -s "$XVFBARGS" python -m unittest discover -v -b .
