# https://packaging.python.org/en/latest/appveyor/

skip_commits:
  files:
    - doc/*
    - .travis.yml

clone_depth: 30

matrix:
  fast_finish: true

environment:
  global:
    PROJECT_NAME: "orange-widget-base"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    BUILD_DEP: wheel==0.29.0 pip~=19.0.0
    TEST_DEP: PyQt5~=5.9.2

  matrix:
    - PYTHON: C:\Python36-x64

    - PYTHON: C:\Python37-x64
      TEST_DEP: PyQt5~=5.12.1 PyQtWebEngine~=5.12.1

cache:
  - '%LOCALAPPDATA%\pip\cache -> appveyor.yml'

install:
  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  - python -m pip install %BUILD_DEP%
  - python -m pip --version
  - python -m pip list --format=freeze

build_script:
  # get the package version
  - for /f %%f in ('python setup.py --version') do ( set "VERSION=%%f" )
  - python setup.py %BDIST_WHEEL_GLOBAL_OPTIONS% bdist_wheel

test_script:
  - python -m venv --clear build\.test
  - build\.test\Scripts\activate
  - cd build\.test
  # Pre-populate the test environment
  - python -m pip install pip~=19.0.0 wheel

  - python -m pip install %TEST_DEP%
  - python -m pip install --no-index --no-deps -f ..\..\dist --pre %PROJECT_NAME%==%VERSION%
  - python -m pip install %PROJECT_NAME%==%VERSION%
  - python -m pip list --format=freeze
  - python -m unittest discover -v -b orangewidget
  - cd ..\..

artifacts:
  - path: dist\*.whl
